route:
  receiver: telegram
  group_by: [''alertname'']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 30m

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: ${TELEGRAM_BOT_TOKEN}
        chat_id: ${TELEGRAM_CHAT_ID}
        parse_mode: Markdown
        message: |
          *{{ .CommonAnnotations.summary }}*

          {{ .CommonAnnotations.description }}
          Labels: {{ range $k, $v := .CommonLabels }}{{ $k }}={{ $v }} {{ end }}

templates: []
